### ISSUE TITLE
Mod Overwriting

### ISSUE THREAD

**Issue by armpit** [sedenion/ovgme#22]
When you enable a mod that over overwrites another mod and then disable it the overwritten files will be replaced by the files that where overwritten by the first mod.

Example:

Mod 1 replaces original 'config.xml'
Mod 2 also contains 'config.xml' and overwrites the one from mod 1

If you disable mod 2 then the original 'config.xml' will be re-instated possibly breaking mod 1

The backup system should track the order and return the filesystem to the correct state from before the mod was enabled.

**Comment by sedenion** [comment]
I know, and this is a design choice. OvGME was not designed to handle mod overlapping in cumulative and ordered way, but in random way, and to ensure the genuine app/game file could always be restored whatever what the mods installation and restoration order. The side effect of this choice is what you mentioned.

Another design choice, which is the one chosen by JSGME, is to make a copy of the file as it is in the app/game folder, at mod installation, which allow, if you take care to uninstall mods in the right order, to keep the previously installed mod without corruption. The side effect of this is to me more dangerous: the risk of definitly losing the genuine app/game file, if mods are not restored in the proper order.

To do what you suggest in the proper and secure way, we have to build a dependency tree architecture (OvGME would need a deep refactoring to implement that).  In this case, the mod installation order is tracked, but if you want to uninstall a mod, the software will tell you that you need, for example, uninstall this previous one in order to uninstall the one you want: you will be forced to uninstall the two mods, or maybe the three, four or five mods, depending the dependency tree. This is approximately what JSGME does, and i don't know its reliability of managing three, four or five overlapping.

And at this stage, the software would simply forces you to don't do stupid things, but if you want the software to be smart for you (what most user want), for example, to allow you to uninstall any mod in random way, and always keeping coherence between backups and installed files, the software must, for you, uninstall all dependency tree, then reinstall the mods in the previous order, without the desired mod, to create a new dependency tree. At this stage, the process could potentially induce massive hard disk activity behind the scene, or a very smart conditionnal algorithm, close to I.A, to optimize files swaps. Many users don't realize that mod overlapping is a way more complex problem than what it appear to be.

**Comment by armpit** [comment]
No worries, it's not a game breaker. I pretty much expected an answer similar to this. It's not hard to work around anyway and probably would not affect your average user.
