### ISSUE TITLE
Repository implementation

### ISSUE THREAD

**Issue by mguegan** [sedenion/ovgme#5]
Hi Sedenion,

Thanks for OvGME, this is really a nice piece of work. I wonder why you've implemented the network stack at low-level for grabbing internet files and not using something like 'curl'  ? It would allow you to use multiple protocols (HTTPS) easily by letting the tool doing its best.

I've done some test yesterday and it seems I've found a bug when trying to grab multiple mods (some weird 404's) :

``
"GET /ovgme/476th%20-%20Grease%20Pencil%20Tip-In%20References.zip HTTP/1.1" 200 5594744 "-" "-" "-"
``
``
"GET /ovgme/Toubib%27s%20canopy%20references.zipIn%20References.zip HTTP/1.1" 404 162 "-" "-" "-"
``

As you can see, ``In%20References.zip`` is added at the end of the second mods file, looks like a weird memory bug. I'm pretty sure that's the content of my .xml file is correct though.

Speaking of XML, it would be nice to have a more user-friendly config file, like JSON or YAML, but that's another story and purely a personal preference. Don't take me wrong, you already have done a fantastic work, I'm just trying to share my thoughts with you.

**Comment by sedenion** [comment]
Hi,

i simply don't thought about libcurl (curl was, in my mind, only a command line tool, not a lib), and i love to make things at low level when possible. Using big library is sometime like using a missile to shoot a fly... So i have to look at this libcurl, to see if it is realy more easy or not.

I think i found the origin of the memory bug for file URL, please try the last build (today at 11h20 AM, Paris houre), i think it is fixed.

I choosen XML, first because i already know a lightweigh XML c++ parser, but for JSON never looked at (in c++ at least), idem for YAML (which i did not even know).  Which one is more user-friendly depends on user i think :) XML is probably a little more boring to write... but it is near to HTML, a well known syntax which don't let ambiguity (the syntax is hugly, but clear). In the other hand, for human reading, JSON or YAML syntax become quickly confusing (my opinion), BUT, built-in functions are available for serialization (for Json in javascript at least, for YAML i don't know). But these functions are only known by advanced web developpers. At this point, an XML source generator in PHP is not so hard to implement.

**Comment by sedenion** [comment]
(( Just having a look to libcurl... as i espected, this is a typical "big library" (which include  A LOT of things that i will never use [FTP, Imap, POP, SSH... ho my...]) not easy to include into this kind of project...  the library must be either compiled separatly, or be embeded as source code in the project, (many files) and, this is very boring... Talking in raw HTTP to servers using standard TCP/IP stack is easier at this stage (if we exclude HTTPS, which is a totaly different advanture) ))

**Comment by mguegan** [comment]
Well, I was thinking about `curl.exe` which seems quite ugly in a developer perspective, but certainly faster to implement/distribute and you will have HTTPS support, maybe HTTP/2.0, in fact all of [that.](https://curl.haxx.se/docs/features.html) So yes, it could be the fight between 'hammer to hit a fly' vs 'reinvent the wheel' if you see what I mean. Anyway, I see why you want to implement all the protocols by yourself. About XML vs JSON vs YAML, yes, purely a subjective opinion, sometimes I felt strange writing so much XML code just for a key=value pair. About the memory bug, I will do some testing with the latest version tonight or tomorrow, thanks for the quick fix ! by the way we can have a chat if you want (I'm from France too).

**Comment by sedenion** [comment]
Using curl.exe (shell call) through a compiled program is a kind of nonsense... it is possible, but in this precise case, it is not only ugly, it is almost unusable since by this way, we have absolutly no controls on the download process, no progress callback, no way to know when the download is done nor failed, etc...  No, the standard way, is to use libcurl, which seem pretty cool, if we achieve to compile it as we need it, then link it either  static or dynamic way... If there is realy a need, i will think about spending a week-end on that question, but for now, the current basic implementation is sufficient (except it does not support HTTPS)... and HTTPS is not needed for what OvGME does (in fact, HTTPS is useless for 99% of websites, but business of SSL certs is a gold mine for SSL certs providers (norton and Thawte thank Google for launching this fashion of the "green padlock" icon)). Idem for HTTP/2.0... HTTP/2.0 is a benefit only for complexe webpages with lot of contents to download in paralelle way... OvGME only download very simple data and don't need to display a webpage full of HTML5 with canvas, images and sounds...

**Comment by mguegan** [comment]
Well, you're right about `curl.exe`, that's definitely not a solution, was stupid to propose that. Agreed with what you said, well.. not totally about the HTTPS part (hosting companies are promoting letsencrypt.org nowadays, which is free), and I think the HTTPS problem is not really a matter of what ppl need with OvGME but a matter of default configuration / activation with web servers / hosting services.

**Comment by sedenion** [comment]
Most commercial or big website servers are HTTPS... but the great majority of "normal people" servers are HTTP... I will wait for a stable version... it still some bugs and optimisation issues in the current version (i just corrected an ugly process). When the basis is OK, i will spend time on curl to allow HTTPS...

**Comment by mguegan** [comment]
Ok just tested the repository with the pre-release version (1.6.3) and I confirm you have successfully resolved the bug. Thanks again !
