### ISSUE TITLE
Error in Repo Query

### ISSUE THREAD

**Issue by freebirddz** [sedenion/ovgme#9]
Hello thank you for this tool.
The issue is the following:
1. Any small change in description the generated XML repo file, show an error :
"Repository XML error:No Mod-Descriptor child node found."
But if I rollback or copy the text of any good XML Child MOD it run

2.Text in description but format i think is the return line Char at the end of the line.
![1](https://cloud.githubusercontent.com/assets/23531334/20404033/70ecd638-ad03-11e6-9077-e1fd7e4582dd.png)
![2](https://cloud.githubusercontent.com/assets/23531334/20404035/7504b34e-ad03-11e6-8906-2b623efe01b8.png)

Keep going GREAT JOB, Folks

**Comment by sedenion** [comment]
1. Can you please detail what do you do step by step to reproduce the bug ?
2. Is the problem allways here, or after any edit of the XML file ?

**Comment by adhocine** [comment]
hello,
that's happened when i try to create a web repository for multiple MODs.
I compressed the mods and I added some text in description (like in the picture bellow), when i try to query the remote (the hosted repo) i got that Waring whit out getting any query result.
Perhaps i did it wrong !! but i still getting that Warning.

thankx

**Comment by sedenion** [comment]
I think what you are talking about is another problem. The original problem mentionned in this thread was fixed in the last release (1.6.8), can you please:
1 - verify you use the last vesion
2 - If the problem still here, open a new Issue and give me some details, exact error message, URL used for the repos, and XML file content.
